2023-02-19 16:00:25,844 INFO    StreamThr :3916315 [internal.py:wandb_internal():87] W&B internal server running at pid: 3916315, started at: 2023-02-19 16:00:25.842603
2023-02-19 16:00:25,846 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: status
2023-02-19 16:00:25,847 INFO    WriterThread:3916315 [datastore.py:open_for_write():85] open: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/run-4vcm33so.wandb
2023-02-19 16:00:25,848 DEBUG   SenderThread:3916315 [sender.py:send():336] send: header
2023-02-19 16:00:25,849 DEBUG   SenderThread:3916315 [sender.py:send():336] send: run
2023-02-19 16:00:26,374 INFO    SenderThread:3916315 [dir_watcher.py:__init__():216] watching files in: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files
2023-02-19 16:00:26,374 INFO    SenderThread:3916315 [sender.py:_start_run_threads():1067] run started: 4vcm33so with start time 1676811624.860462
2023-02-19 16:00:26,374 DEBUG   SenderThread:3916315 [sender.py:send_request():363] send_request: summary_record
2023-02-19 16:00:26,375 INFO    SenderThread:3916315 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-02-19 16:00:26,377 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: check_version
2023-02-19 16:00:26,377 DEBUG   SenderThread:3916315 [sender.py:send_request():363] send_request: check_version
2023-02-19 16:00:26,584 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: run_start
2023-02-19 16:00:26,585 DEBUG   HandlerThread:3916315 [system_info.py:__init__():31] System info init
2023-02-19 16:00:26,585 DEBUG   HandlerThread:3916315 [system_info.py:__init__():46] System info init done
2023-02-19 16:00:26,585 INFO    HandlerThread:3916315 [system_monitor.py:start():151] Starting system monitor
2023-02-19 16:00:26,585 INFO    SystemMonitor:3916315 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-02-19 16:00:26,586 INFO    HandlerThread:3916315 [system_monitor.py:probe():172] Collecting system info
2023-02-19 16:00:26,586 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started cpu
2023-02-19 16:00:26,586 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started disk
2023-02-19 16:00:26,586 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started gpu
2023-02-19 16:00:26,587 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started memory
2023-02-19 16:00:26,587 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started network
2023-02-19 16:00:26,615 DEBUG   HandlerThread:3916315 [system_info.py:probe():195] Probing system
2023-02-19 16:00:26,615 DEBUG   HandlerThread:3916315 [system_info.py:_probe_git():180] Probing git
2023-02-19 16:00:26,630 DEBUG   HandlerThread:3916315 [system_info.py:_probe_git():188] Probing git done
2023-02-19 16:00:26,630 DEBUG   HandlerThread:3916315 [system_info.py:probe():241] Probing system done
2023-02-19 16:00:26,630 DEBUG   HandlerThread:3916315 [system_monitor.py:probe():181] {'os': 'Linux-5.15.0-56-generic-x86_64-with-glibc2.29', 'python': '3.8.10', 'heartbeatAt': '2023-02-19T13:00:26.615309', 'startedAt': '2023-02-19T13:00:17.795151', 'docker': None, 'cuda': None, 'args': None, 'state': 'running', 'program': 'GCN_model.ipynb', 'root': '/home/vdshk/SecondaryStructurePredictionGNN', 'git': {'remote': 'https://github.com/Anya497/SecondaryStructurePredictionGNN', 'commit': '49a2ef7741d77ff169fece6e2a5e3131b312541e'}, 'email': 'pogozhelskaya@gmail.com', 'host': 'UNIT-614', 'username': 'vdshk', 'executable': '/home/vdshk/SecondaryStructurePredictionGNN/venv/bin/python3', 'cpu_count': 4, 'cpu_count_logical': 4, 'cpu_freq': {'current': 1020.4907499999999, 'min': 800.0, 'max': 3900.0}, 'cpu_freq_per_core': [{'current': 800.0, 'min': 800.0, 'max': 3900.0}, {'current': 900.0, 'min': 800.0, 'max': 3900.0}, {'current': 1481.963, 'min': 800.0, 'max': 3900.0}, {'current': 900.0, 'min': 800.0, 'max': 3900.0}], 'disk': {'total': 110.1884994506836, 'used': 33.29387283325195}, 'gpu': 'NVIDIA GeForce GTX 1070', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1070', 'memory_total': 8589934592}], 'memory': {'total': 15.293502807617188}}
2023-02-19 16:00:26,631 INFO    HandlerThread:3916315 [system_monitor.py:probe():182] Finished collecting system info
2023-02-19 16:00:26,631 INFO    HandlerThread:3916315 [system_monitor.py:probe():185] Publishing system info
2023-02-19 16:00:26,631 DEBUG   HandlerThread:3916315 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-02-19 16:00:26,631 DEBUG   HandlerThread:3916315 [system_info.py:_save_pip():67] Saving pip packages done
2023-02-19 16:00:26,632 INFO    HandlerThread:3916315 [system_monitor.py:probe():187] Finished publishing system info
2023-02-19 16:00:26,632 DEBUG   SenderThread:3916315 [sender.py:send():336] send: files
2023-02-19 16:00:26,633 INFO    SenderThread:3916315 [sender.py:_save_file():1321] saving file wandb-metadata.json with policy now
2023-02-19 16:00:26,644 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: stop_status
2023-02-19 16:00:26,646 DEBUG   SenderThread:3916315 [sender.py:send_request():363] send_request: stop_status
2023-02-19 16:00:26,649 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: pause
2023-02-19 16:00:26,649 INFO    HandlerThread:3916315 [handler.py:handle_request_pause():717] stopping system metrics thread or process
2023-02-19 16:00:26,649 INFO    HandlerThread:3916315 [system_monitor.py:finish():161] Stopping system monitor
2023-02-19 16:00:26,655 DEBUG   SystemMonitor:3916315 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-02-19 16:00:26,657 DEBUG   SystemMonitor:3916315 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2023-02-19 16:00:26,659 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined cpu
2023-02-19 16:00:26,662 DEBUG   SystemMonitor:3916315 [system_monitor.py:_start():141] Publishing last batch of metrics
2023-02-19 16:00:26,663 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined disk
2023-02-19 16:00:26,703 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined gpu
2023-02-19 16:00:26,704 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined memory
2023-02-19 16:00:26,704 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined network
2023-02-19 16:00:26,704 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: resume
2023-02-19 16:00:26,704 INFO    HandlerThread:3916315 [handler.py:handle_request_resume():708] starting system metrics thread or process
2023-02-19 16:00:26,704 INFO    HandlerThread:3916315 [system_monitor.py:start():151] Starting system monitor
2023-02-19 16:00:26,704 INFO    SystemMonitor:3916315 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-02-19 16:00:26,704 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: pause
2023-02-19 16:00:26,704 INFO    HandlerThread:3916315 [handler.py:handle_request_pause():717] stopping system metrics thread or process
2023-02-19 16:00:26,704 INFO    HandlerThread:3916315 [system_monitor.py:finish():161] Stopping system monitor
2023-02-19 16:00:26,705 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started cpu
2023-02-19 16:00:26,705 DEBUG   SystemMonitor:3916315 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-02-19 16:00:26,705 DEBUG   SystemMonitor:3916315 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2023-02-19 16:00:26,705 DEBUG   SystemMonitor:3916315 [system_monitor.py:_start():141] Publishing last batch of metrics
2023-02-19 16:00:26,705 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined cpu
2023-02-19 16:00:26,705 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: resume
2023-02-19 16:00:26,705 INFO    HandlerThread:3916315 [handler.py:handle_request_resume():708] starting system metrics thread or process
2023-02-19 16:00:26,705 INFO    HandlerThread:3916315 [system_monitor.py:start():151] Starting system monitor
2023-02-19 16:00:26,705 INFO    SystemMonitor:3916315 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-02-19 16:00:26,706 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started cpu
2023-02-19 16:00:26,706 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started disk
2023-02-19 16:00:26,706 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started gpu
2023-02-19 16:00:26,706 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started memory
2023-02-19 16:00:26,707 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started network
2023-02-19 16:00:26,819 DEBUG   SenderThread:3916315 [sender.py:send():336] send: telemetry
2023-02-19 16:00:26,819 DEBUG   SenderThread:3916315 [sender.py:send():336] send: stats
2023-02-19 16:00:26,819 DEBUG   SenderThread:3916315 [sender.py:send():336] send: stats
2023-02-19 16:00:27,153 INFO    wandb-upload_0:3916315 [upload_job.py:push():138] Uploaded file /tmp/tmpus1e0hihwandb/1ntmmd3v-wandb-metadata.json
2023-02-19 16:00:27,376 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_created():275] file/dir created: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/wandb-summary.json
2023-02-19 16:00:27,376 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_created():275] file/dir created: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/wandb-metadata.json
2023-02-19 16:00:27,377 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_created():275] file/dir created: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:27,377 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_created():275] file/dir created: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/requirements.txt
2023-02-19 16:00:29,376 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:30,924 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: status_report
2023-02-19 16:00:31,376 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:32,945 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: partial_history
2023-02-19 16:00:32,946 DEBUG   SenderThread:3916315 [sender.py:send():336] send: history
2023-02-19 16:00:32,946 DEBUG   SenderThread:3916315 [sender.py:send_request():363] send_request: summary_record
2023-02-19 16:00:32,946 INFO    SenderThread:3916315 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-02-19 16:00:33,377 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/wandb-summary.json
2023-02-19 16:00:33,377 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:34,377 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:35,377 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:35,970 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: status_report
2023-02-19 16:00:37,378 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:39,170 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: partial_history
2023-02-19 16:00:39,171 DEBUG   SenderThread:3916315 [sender.py:send():336] send: history
2023-02-19 16:00:39,172 DEBUG   SenderThread:3916315 [sender.py:send_request():363] send_request: summary_record
2023-02-19 16:00:39,172 INFO    SenderThread:3916315 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-02-19 16:00:39,378 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/wandb-summary.json
2023-02-19 16:00:39,378 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:40,378 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:40,986 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: status_report
2023-02-19 16:00:41,379 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:41,644 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:00:43,379 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:45,380 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:45,472 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: partial_history
2023-02-19 16:00:45,473 DEBUG   SenderThread:3916315 [sender.py:send():336] send: history
2023-02-19 16:00:45,473 DEBUG   SenderThread:3916315 [sender.py:send_request():363] send_request: summary_record
2023-02-19 16:00:45,473 INFO    SenderThread:3916315 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-02-19 16:00:45,994 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: status_report
2023-02-19 16:00:46,380 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/wandb-summary.json
2023-02-19 16:00:46,380 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:46,644 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:00:47,380 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:49,381 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:51,000 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: status_report
2023-02-19 16:00:51,381 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:51,645 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:00:51,756 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: partial_history
2023-02-19 16:00:51,757 DEBUG   SenderThread:3916315 [sender.py:send():336] send: history
2023-02-19 16:00:51,757 DEBUG   SenderThread:3916315 [sender.py:send_request():363] send_request: summary_record
2023-02-19 16:00:51,757 INFO    SenderThread:3916315 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-02-19 16:00:52,382 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/wandb-summary.json
2023-02-19 16:00:52,382 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:53,382 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:54,382 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:55,382 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:56,031 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: status_report
2023-02-19 16:00:56,274 ERROR   SenderThread:3916315 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-02-19 16:00:56,274 ERROR   SenderThread:3916315 [internal_api.py:execute():246] {"errors":[{"message":"run chi-vinny0702/secondary_structure_prediction/4vcm33so was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-19 16:00:56,646 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:00:57,383 INFO    Thread-61 :3916315 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/files/output.log
2023-02-19 16:00:58,054 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: partial_history
2023-02-19 16:00:58,148 ERROR   SenderThread:3916315 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-02-19 16:00:58,148 ERROR   SenderThread:3916315 [internal_api.py:execute():246] {"errors":[{"message":"run chi-vinny0702/secondary_structure_prediction/4vcm33so was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-19 16:01:00,534 ERROR   SenderThread:3916315 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-02-19 16:01:00,534 ERROR   SenderThread:3916315 [internal_api.py:execute():246] {"errors":[{"message":"run chi-vinny0702/secondary_structure_prediction/4vcm33so was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-19 16:01:00,534 INFO    SenderThread:3916315 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 242, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-02-19 16:01:01,646 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:01:03,763 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: pause
2023-02-19 16:01:03,763 INFO    HandlerThread:3916315 [handler.py:handle_request_pause():717] stopping system metrics thread or process
2023-02-19 16:01:03,763 INFO    HandlerThread:3916315 [system_monitor.py:finish():161] Stopping system monitor
2023-02-19 16:01:03,763 DEBUG   SystemMonitor:3916315 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-02-19 16:01:03,763 DEBUG   SystemMonitor:3916315 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2023-02-19 16:01:03,763 DEBUG   SystemMonitor:3916315 [system_monitor.py:_start():141] Publishing last batch of metrics
2023-02-19 16:01:03,764 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined cpu
2023-02-19 16:01:03,764 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined disk
2023-02-19 16:01:03,800 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined gpu
2023-02-19 16:01:03,800 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined memory
2023-02-19 16:01:03,801 INFO    HandlerThread:3916315 [interfaces.py:finish():175] Joined network
2023-02-19 16:01:05,187 ERROR   SenderThread:3916315 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-02-19 16:01:05,188 ERROR   SenderThread:3916315 [internal_api.py:execute():246] {"errors":[{"message":"run chi-vinny0702/secondary_structure_prediction/4vcm33so was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-19 16:01:06,652 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:01:10,541 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: resume
2023-02-19 16:01:10,542 INFO    HandlerThread:3916315 [handler.py:handle_request_resume():708] starting system metrics thread or process
2023-02-19 16:01:10,542 INFO    HandlerThread:3916315 [system_monitor.py:start():151] Starting system monitor
2023-02-19 16:01:10,542 INFO    SystemMonitor:3916315 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-02-19 16:01:10,542 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started cpu
2023-02-19 16:01:10,542 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started disk
2023-02-19 16:01:10,544 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started gpu
2023-02-19 16:01:10,547 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started memory
2023-02-19 16:01:10,547 INFO    SystemMonitor:3916315 [interfaces.py:start():168] Started network
2023-02-19 16:01:11,558 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: poll_exit
2023-02-19 16:01:14,749 ERROR   SenderThread:3916315 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-02-19 16:01:14,750 ERROR   SenderThread:3916315 [internal_api.py:execute():246] {"errors":[{"message":"run chi-vinny0702/secondary_structure_prediction/4vcm33so was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-19 16:01:16,559 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:01:21,561 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:01:26,562 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:01:31,563 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:01:33,771 ERROR   SenderThread:3916315 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-02-19 16:01:33,772 ERROR   SenderThread:3916315 [internal_api.py:execute():246] {"errors":[{"message":"run chi-vinny0702/secondary_structure_prediction/4vcm33so was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-19 16:01:36,564 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:01:41,565 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:01:46,567 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:01:51,568 DEBUG   HandlerThread:3916315 [handler.py:handle_request():144] handle_request: keepalive
2023-02-19 16:02:08,325 ERROR   SenderThread:3916315 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-02-19 16:02:08,325 ERROR   SenderThread:3916315 [internal_api.py:execute():246] {"errors":[{"message":"run chi-vinny0702/secondary_structure_prediction/4vcm33so was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-19 16:02:10,548 DEBUG   SystemMonitor:3916315 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-02-19 16:02:50,581 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:50,582 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:50,587 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:50,587 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:50,986 WARNING StreamThr :3916315 [internal.py:is_dead():415] Internal process exiting, parent pid 3916288 disappeared
2023-02-19 16:02:50,987 ERROR   StreamThr :3916315 [internal.py:wandb_internal():153] Internal process shutdown.
2023-02-19 16:02:51,551 INFO    HandlerThread:3916315 [handler.py:finish():841] shutting down handler
2023-02-19 16:02:51,552 INFO    WriterThread:3916315 [datastore.py:close():299] close: /home/vdshk/SecondaryStructurePredictionGNN/wandb/run-20230219_160017-4vcm33so/run-4vcm33so.wandb
2023-02-19 16:02:52,582 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:52,583 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:52,588 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:52,588 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:54,583 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:54,584 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:54,589 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:54,589 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:56,585 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:56,585 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:56,591 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:56,591 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:58,586 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:58,587 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:58,592 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:02:58,592 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:00,587 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:00,588 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:00,593 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:00,594 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:02,589 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:02,589 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:02,594 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:02,595 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:04,590 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:04,591 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:04,595 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:04,596 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:06,591 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:06,591 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:06,596 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:06,596 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:08,592 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:08,593 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:08,597 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:08,598 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:10,593 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:10,593 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:10,600 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:10,601 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:12,594 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:12,595 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:12,601 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:12,602 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:14,595 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:14,596 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:14,602 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:14,603 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:16,597 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:16,597 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:16,603 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:16,603 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:18,597 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:18,598 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:18,604 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:18,604 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:20,599 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:20,600 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:20,605 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:20,605 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:21,983 ERROR   SenderThread:3916315 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-02-19 16:03:21,984 ERROR   SenderThread:3916315 [internal_api.py:execute():246] {"errors":[{"message":"run chi-vinny0702/secondary_structure_prediction/4vcm33so was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-02-19 16:03:21,984 ERROR   StreamThr :3916315 [internal.py:wandb_internal():175] Thread SenderThread:
Traceback (most recent call last):
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 242, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1593, in upsert_run
    response = self.gql(
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 214, in gql
    ret = self._retry_gql(
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 247, in execute
    self.display_gorilla_error_if_found(res)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 263, in display_gorilla_error_if_found
    wandb.termerror(
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/errors/term.py", line 61, in termerror
    _log(
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/errors/term.py", line 95, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/click/utils.py", line 300, in echo
    file.flush()
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 335, in _debounce
    self._sm.debounce()
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 512, in debounce
    self._maybe_update_config(always=final)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 489, in _maybe_update_config
    self._debounce_config()
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 518, in _debounce_config
    self._api.upsert_run(
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/apis/normalize.py", line 64, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1593, in upsert_run
    response = self.gql(
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 214, in gql
    ret = self._retry_gql(
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 247, in execute
    self.display_gorilla_error_if_found(res)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 263, in display_gorilla_error_if_found
    wandb.termerror(
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/errors/term.py", line 61, in termerror
    _log(
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/wandb/errors/term.py", line 95, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/vdshk/SecondaryStructurePredictionGNN/venv/lib/python3.8/site-packages/click/utils.py", line 300, in echo
    file.flush()
wandb.errors.CommError: [Errno 32] Broken pipe
2023-02-19 16:03:22,600 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:22,600 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:22,605 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:22,606 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:24,601 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:24,602 ERROR   cpu       :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:24,606 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:24,607 ERROR   memory    :3916315 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=3916288)
2023-02-19 16:03:25,010 INFO    MainThread:3916315 [internal.py:handle_exit():77] Internal process exited
2023-02-19 16:03:25,010 INFO    MainThread:3916315 [internal.py:handle_exit():77] Internal process exited
2023-02-19 16:03:25,010 INFO    MainThread:3916315 [internal.py:handle_exit():77] Internal process exited
2023-02-19 16:03:25,011 INFO    MainThread:3916315 [internal.py:handle_exit():77] Internal process exited
2023-02-19 16:03:25,011 INFO    MainThread:3916315 [internal.py:handle_exit():77] Internal process exited
